In [1]:
import pandas as pd
import numpy as np

In [2]:
pwd

'C:\\Users\\AKM098\\OneDrive - Maersk Group\\Data_Science\\End-to-End-implementation\\Deploy-FastAPI'

In [3]:
df = pd.read_csv ('data/BankNote_Authentication.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [6]:
df.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [7]:
df['class'].value_counts()

class
0    762
1    610
Name: count, dtype: int64

In [8]:
df.shape

(1372, 5)

In [5]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [8]:
#model building
from sklearn.ensemble import RandomForestClassifier

In [9]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [10]:
rf.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,

In [11]:
rf.predict_proba(X_test)

array([[1.  , 0.  ],
       [0.98, 0.02],
       [0.91, 0.09],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.97, 0.03],
       [0.83, 0.17],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.02, 0.98],
       [0.  , 1.  ],
       [0.91, 0.09],
       [0.05, 0.95],
       [0.91, 0.09],
       [0.02, 0.98],
       [0.02, 0.98],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.06, 0.94],
       [1.  , 0.  ],
       [0.97, 0.03],
       [0.04, 0.96],
       [1.  , 0.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.97, 0.03],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.97, 0.03],
       [0.1 , 0.9 ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.09, 0.91],
       [0.07, 0.93],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.04, 0.96],
       [0.97, 0.03],
       [0.01, 0.99],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.99,

In [16]:
np.max(rf.predict_proba(X_test), axis=1)

array([0.99, 0.98, 0.93, 1.  , 1.  , 1.  , 1.  , 0.93, 1.  , 0.99, 0.93,
       1.  , 0.88, 0.96, 0.86, 1.  , 1.  , 1.  , 1.  , 0.97, 1.  , 0.96,
       0.97, 1.  , 1.  , 1.  , 1.  , 1.  , 0.94, 1.  , 1.  , 1.  , 0.97,
       0.89, 0.97, 1.  , 0.84, 0.94, 1.  , 1.  , 0.99, 1.  , 0.96, 0.95,
       1.  , 1.  , 1.  , 1.  , 1.  , 0.97, 1.  , 0.97, 0.99, 1.  , 1.  ,
       0.99, 0.99, 1.  , 1.  , 1.  , 1.  , 1.  , 0.99, 1.  , 1.  , 1.  ,
       1.  , 0.99, 0.54, 0.98, 0.91, 1.  , 0.96, 0.98, 0.53, 0.98, 0.99,
       0.97, 1.  , 0.93, 1.  , 0.95, 1.  , 0.99, 1.  , 1.  , 1.  , 1.  ,
       0.99, 1.  , 1.  , 1.  , 0.89, 1.  , 1.  , 0.99, 1.  , 0.94, 1.  ,
       0.82, 1.  , 1.  , 1.  , 1.  , 0.87, 1.  , 1.  , 0.99, 1.  , 1.  ,
       0.98, 0.86, 1.  , 0.93, 0.9 , 1.  , 1.  , 0.99, 1.  , 0.99, 0.99,
       1.  , 0.84, 1.  , 0.94, 1.  , 1.  , 1.  , 0.98, 1.  , 0.86, 1.  ,
       0.94, 0.99, 1.  , 1.  , 1.  , 1.  , 1.  , 0.97, 1.  , 1.  , 0.98,
       0.99, 0.96, 0.84, 0.99, 0.98, 0.99, 1.  , 0.

In [17]:
rf.predict_log_proba(X_test)

C:\Users\AKM098\AppData\Local\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py:910: RuntimeWarning: divide by zero encountered in log
  return np.log(proba)


array([[-0.01005034, -4.60517019],
       [-0.02020271, -3.91202301],
       [-0.07257069, -2.65926004],
       [ 0.        ,        -inf],
       [ 0.        ,        -inf],
       [ 0.        ,        -inf],
       [ 0.        ,        -inf],
       [-0.07257069, -2.65926004],
       [ 0.        ,        -inf],
       [-0.01005034, -4.60517019],
       [-2.65926004, -0.07257069],
       [       -inf,  0.        ],
       [-0.12783337, -2.12026354],
       [-3.21887582, -0.04082199],
       [-0.15082289, -1.96611286],
       [       -inf,  0.        ],
       [       -inf,  0.        ],
       [       -inf,  0.        ],
       [       -inf,  0.        ],
       [-3.5065579 , -0.03045921],
       [ 0.        ,        -inf],
       [-0.04082199, -3.21887582],
       [-3.5065579 , -0.03045921],
       [ 0.        ,        -inf],
       [       -inf,  0.        ],
       [ 0.        ,        -inf],
       [ 0.        ,        -inf],
       [       -inf,  0.        ],
       [-0.0618754 ,

In [18]:
pwd

'C:\\Users\\AKM098\\OneDrive - Maersk Group\\Data_Science\\End-to-End-implementation\\Deploy-FastAPI'

In [12]:
import pickle

In [13]:
#create pickle file
pickle.dump(rf, open('new_model.pkl', 'wb'))

In [14]:
rf_pkl_model = pickle.load(open('new_model.pkl', 'rb'))

In [15]:
rf_pkl_model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,

In [31]:
from BankNotes import BankNote

In [32]:
data:BankNote

In [34]:
def predict_banknote(data:BankNote):
    data = data.dict()
    variance=data['variance']
    skewness=data['skewness']
    curtosis=data['curtosis']
    entropy=data['entropy']
    print(variance, skewness, curtosis, entropy)